import { constants as fsConstants } from "node:fs";
import { access, copyFile, mkdir, readdir, realpath, writeFile } from "node:fs/promises";
import { basename, dirname, isAbsolute, join, relative, resolve, sep } from "node:path";
import { count, displayDate } from "./format.js";
import { demaskText } from "./mask.js";
import type { Vault } from "./vault.js";
import {
  WORKFLOW_INPUTS,
  stepById,
  type InputKey,
} from "./workflow-registry.js";
import type { WorkflowManifest, WorkflowPass } from "./workflow-state.js";

/**
 * Packaging helpers for the audit workflow's pass folders: collision-free
 * paths, guarded copies, path-containment assertions, findings counting,
 * the auto narrative, the findings CSV and the two per-pass artifacts
 * (INDEX.md and summary.json). Formatting-only code — the runner decides
 * when each piece is written.
 */

const exists = async (p: string): Promise<boolean> => {
  try {
    await access(p);
    return true;
  } catch {
    return false;
  }
};

/** A path in `dir` that does not exist yet: `a.xlsx`, then `a (2).xlsx`, … */
export async function uniquePath(dir: string, name: string): Promise<string> {
  const ext = name.lastIndexOf(".") > 0 ? name.slice(name.lastIndexOf(".")) : "";
  const stem = ext ? name.slice(0, name.length - ext.length) : name;
  let candidate = join(dir, name);
  for (let n = 2; (await exists(candidate)); n++) {
    candidate = join(dir, `${stem} (${n})${ext}`);
  }
  return candidate;
}

/**
 * Copy `src` into `dstDir` under its own name, never overwriting: when the
 * name is taken the copy becomes `name (2).ext` next to it.
 */
export async function copyNoClobber(src: string, dstDir: string): Promise<string> {
  await mkdir(dstDir, { recursive: true });
  const name = basename(src);
  const dst = (await exists(join(dstDir, name)))
    ? await uniquePath(dstDir, name)
    : join(dstDir, name);
  await copyFile(src, dst, fsConstants.COPYFILE_EXCL);
  return dst;
}

/**
 * Refuse to touch anything outside `root`, resolving symlinks on the nearest
 * existing ancestor of `p`. Returns the resolved path when safe.
 */
export async function assertInside(root: string, p: string): Promise<string> {
  const realRoot = await realpath(root);
  const abs = resolve(p);
  const outside = () => new Error(`refusing to touch a path outside the workflow folder: ${p}`);
  let probe = abs;
  for (;;) {
    try {
      const real = await realpath(probe);
      const rel = relative(realRoot, real);
      if (rel.startsWith("..") || isAbsolute(rel)) throw outside();
      return abs;
    } catch (e) {
      if (e instanceof Error && e.message.startsWith("refusing to touch")) throw e;
      const up = dirname(probe);
      if (up === probe) throw outside();
      probe = up;
    }
  }
}

export type FindingsCounts = { critical: number; warning: number; review: number };

/** Severity counts over a review result's findings array, tolerating junk. */
export function countFindings(result: unknown): FindingsCounts {
  const out: FindingsCounts = { critical: 0, warning: 0, review: 0 };
  const findings = (result as { findings?: unknown } | null | undefined)?.findings;
  if (Array.isArray(findings)) {
    for (const f of findings) {
      const sev = (f as { severity?: unknown } | null)?.severity;
      if (sev === "critical" || sev === "warning" || sev === "review") out[sev] += 1;
    }
  }
  return out;
}

const todayYmd = (): string => new Date().toISOString().slice(0, 10).replace(/-/g, "");

const csvField = (v: unknown): string => {
  const s = String(v ?? "");
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
};

/**
 * The masked, counts-only narrative report writers accept as their markdown.
 * Numbers go through count() (Indian grouping) so no bare 6+-digit run ever
 * reaches the model, and no party name appears by construction.
 */
export function autoNarrative(stepTitle: string, result: unknown): string {
  const counts = countFindings(result);
  const total = counts.critical + counts.warning + counts.review;
  const byCheckSeverity = new Map<string, { check: string; severity: string; n: number }>();
  const findings = (result as { findings?: unknown } | null | undefined)?.findings;
  if (Array.isArray(findings)) {
    for (const f of findings) {
      const check = String((f as { check?: unknown } | null)?.check ?? "unknown");
      const severity = String((f as { severity?: unknown } | null)?.severity ?? "review");
      const k = `${check}|${severity}`;
      const hit = byCheckSeverity.get(k);
      if (hit) hit.n += 1;
      else byCheckSeverity.set(k, { check, severity, n: 1 });
    }
  }
  const lines = [
    `# ${stepTitle}`,
    "",
    `Generated by the tax-audit workflow on ${displayDate(todayYmd())}. ` +
      `${count(total)} findings: ${count(counts.critical)} critical, ` +
      `${count(counts.warning)} warning, ${count(counts.review)} review.`,
    "",
    "| Check | Severity | Findings |",
    "|---|---|---|",
  ];
  const rows = [...byCheckSeverity.values()].sort((a, b) => b.n - a.n);
  for (const r of rows) lines.push(`| ${r.check} | ${r.severity} | ${count(r.n)} |`);
  return lines.join("\n") + "\n";
}

export interface WorkflowCsvFinding {
  id: string;
  check: string;
  severity: string;
  party?: string;
  ledger?: string;
  amount?: number | null;
  detail: string;
}

/** The custom steps' findings.csv: id,check,severity,party,amount,detail. */
export function workflowFindingsCsv(findings: WorkflowCsvFinding[], vault: Vault): string {
  const header = "id,check,severity,party,amount,detail";
  const rows = findings.map((f) =>
    [
      f.id,
      f.check,
      f.severity,
      demaskText(f.party ?? f.ledger ?? "", vault),
      f.amount == null ? "" : f.amount.toFixed(2),
      demaskText(f.detail, vault),
    ]
      .map(csvField)
      .join(","),
  );
  return [header, ...rows].join("\n");
}

const dd = (iso: string): string => {
  const ymd = iso.slice(0, 10).replace(/-/g, "");
  return /^\d{8}$/.test(ymd) ? displayDate(ymd) : iso;
};

const link = (fromDir: string, target: string): string =>
  relative(fromDir, target).split(sep).join("/");

const statusLine = (m: WorkflowManifest, pass: WorkflowPass, id: string): string => {
  const st = m.steps[id] ?? { status: "pending" as const };
  const title = stepById(id)?.title ?? id;
  const carried = pass.recorded?.find((r) => r.id === id && r.state === "carried");
  const findings = st.findings
    ? `${st.findings.critical} critical / ${st.findings.warning} warning / ${st.findings.review} review`
    : "";
  const files = (st.outputs ?? []).map((o) => `[\`${basename(o)}\`](${link(pass.dir, o)})`);
  const notes = [...(st.notes ?? [])];
  if (carried?.carriedFrom) notes.push(`carried forward from ${carried.carriedFrom}`);
  const cells = [
    title,
    st.status,
    findings || "—",
    files.length ? files.join(" ") : "—",
    notes.length ? notes.join("; ") : "—",
  ];
  return `| ${cells.join(" | ")} |`;
};

const inputRows = (m: WorkflowManifest): string[] => {
  const rows: string[] = [];
  for (const [key, entry] of Object.entries(m.inputs)) {
    if (!entry.path) continue;
    rows.push(
      `| ${key} | \`${basename(entry.path)}\` | ${entry.digest ? entry.digest.slice(0, 12) : "—"} |`,
    );
  }
  return rows;
};

/**
 * The per-pass INDEX.md. Only file basenames and digest prefixes appear —
 * never a full input path — and every error string was scrubbed by the
 * runner before it reached the manifest.
 */
export function renderIndex(m: WorkflowManifest, passN: number): string {
  const pass = m.passes.find((p) => p.n === passN);
  const lines: string[] = [];
  lines.push(`# Tax-audit workflow — ${m.params.company}`, "");
  lines.push(`- Period: ${displayDate(m.params.fromDate)} to ${displayDate(m.params.toDate)}`);
  lines.push(`- Pass: ${passN}${pass?.closedAt ? ` (closed ${dd(pass.closedAt)})` : " (in progress)"}`);
  lines.push(`- Tally reachable: ${m.tallyReachable === null ? "unknown" : m.tallyReachable ? "yes" : "no"}`);
  lines.push("");

  lines.push("## Steps", "");
  lines.push("| Step | Status | Findings | Files | Notes |");
  lines.push("|---|---|---|---|---|");
  if (pass) {
    for (const id of pass.plan) lines.push(statusLine(m, pass, id));
    for (const r of pass.recorded ?? []) lines.push(statusLine(m, pass, r.id));
  }
  lines.push("");

  const needs = (pass?.recorded ?? []).filter((r) => r.state === "needs-input");
  if (needs.length) {
    lines.push("## Needs your input", "");
    for (const r of needs) {
      for (const key of r.missing ?? []) {
        const spec = WORKFLOW_INPUTS[key];
        const entry = m.inputs[key];
        const where = entry?.path
          ? `fill \`${basename(entry.path)}\``
          : spec?.howToGet
            ? spec.howToGet
            : "provide the file";
        lines.push(
          `- **${spec?.label ?? key}** — ${where}` +
            (entry?.path ? ` (at \`${basename(entry.path)}\`)` : "") +
            (spec?.doc ? `; see ${spec.doc}` : "") +
            `; blocks step \`${r.id}\``,
        );
      }
    }
    lines.push("");
  }

  const skipped: string[] = [];
  for (const r of pass?.recorded ?? []) {
    if (r.state === "needs-tally") skipped.push(`- ${stepById(r.id)?.title ?? r.id} — Tally is not reachable; run again with Tally open.`);
  }
  for (const id of m.selectedSteps) {
    if (m.steps[id]?.status === "skipped") skipped.push(`- ${stepById(id)?.title ?? id} — deselected.`);
  }
  for (const id of pass?.plan ?? []) {
    for (const note of m.steps[id]?.notes ?? []) {
      if (note.startsWith("skipped: ")) skipped.push(`- ${stepById(id)?.title ?? id} — ${note.slice("skipped: ".length)}`);
    }
  }
  if (skipped.length) {
    lines.push("## Skipped", "", ...skipped, "");
  }

  const failed = (pass?.plan ?? []).filter((id) => m.steps[id]?.status === "failed");
  if (failed.length) {
    lines.push("## Failed", "");
    for (const id of failed) {
      lines.push(`- ${stepById(id)?.title ?? id} — ${m.steps[id]?.error ?? "unknown error"}`);
    }
    lines.push("");
  }

  const used = inputRows(m);
  if (used.length) {
    lines.push("## Inputs used", "");
    lines.push("| Key | File | Digest (first 12) |");
    lines.push("|---|---|---|");
    lines.push(...used, "");
  }
  return lines.join("\n");
}

/** The per-pass summary.json body (the runner stringifies and writes it). */
export function summaryJson(m: WorkflowManifest, passN: number): Record<string, unknown> {
  const pass = m.passes.find((p) => p.n === passN);
  const ids = [...(pass?.plan ?? []), ...(pass?.recorded ?? []).map((r) => r.id)];
  const steps = ids.map((id) => {
    const st = m.steps[id] ?? {};
    return {
      id,
      title: stepById(id)?.title ?? id,
      status: st.status ?? "pending",
      findings: st.findings ?? null,
      outputs: st.outputs ?? [],
      notes: st.notes ?? [],
      error: st.error ?? null,
    };
  });
  const needsInput: Array<Record<string, unknown>> = [];
  for (const r of pass?.recorded ?? []) {
    if (r.state !== "needs-input") continue;
    for (const key of r.missing ?? []) {
      const spec = WORKFLOW_INPUTS[key];
      const entry = m.inputs[key];
      needsInput.push({
        step: r.id,
        key,
        label: spec?.label ?? key,
        path: entry?.path ?? null,
        doc: spec?.doc ?? null,
      });
    }
  }
  return {
    workflowId: m.workflowId,
    company: m.params.company,
    fromDate: m.params.fromDate,
    toDate: m.params.toDate,
    asOnDate: m.params.asOnDate,
    pass: passN,
    startedAt: pass?.startedAt ?? null,
    closedAt: pass?.closedAt ?? null,
    tallyReachable: m.tallyReachable,
    steps,
    needsInput,
    inputs: Object.entries(m.inputs)
      .filter(([, e]) => e.path)
      .map(([key, e]) => ({
        key,
        status: e.status,
        file: basename(e.path as string),
        digest12: e.digest ? e.digest.slice(0, 12) : null,
      })),
  };
}

export async function writeTextFile(path: string, text: string): Promise<void> {
  await writeFile(path, text, "utf8");
}

export async function listDir(path: string): Promise<string[]> {
  try {
    return await readdir(path);
  } catch {
    return [];
  }
}

export type { InputKey };
